### ISSUE TITLE
Trunk fails to build on GCC 4.1.3 (linux)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [edrikL/gears#521]
```
What steps will reproduce the problem?
1. checkout trunk
2. make -k
3. errors occur

What is the expected output? What do you see instead?


fts1_porter.c:
../third_party/sqlite_google/ext/fts1/fts1_porter.c:410: warning: value
computed is not used


.database2/database2.cc:
../gears/database2/transaction.h:110: error: extra qualification
‘Database2Transaction::’ on member ‘Database2Transaction’

Expected: clean compile


What version of the product are you using? On what operating system?

Gears Public rev: 1805

OS: Ubuntu Gutsy 

GCC version: 4.1.3

Browser UA: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.14)
Gecko/20080418 Ubuntu/7.10 (gutsy) Firefox/2.0.0.14

Version/Build: 0.3.24.0;developer;opt;linux;firefox

Please provide any additional information below.
Ubuntu has 4.1.3 by default. Gears compiles with GCC 3.4, but Ubuntu's
binutils seems to have the bug that causes linking to fail.

Compiles and runs if -Werror is disabled. Unittest report no failures.
However, had one weirdly trivial fts -related regression compared to public
versions. 

Compile log attached.


```

Original issue reported on code.google.com by `ktkin...@gmail.com` on 30 May 2008 at 11:20

Attachments:
- [out.txt](https://storage.googleapis.com/google-code-attachments/gears/issue-521/comment-0/out.txt)
