### ISSUE TITLE
SVN rev. 1121 fails to build with g++ 4.2.1.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [edrikL/gears#408]
```
What steps will reproduce the problem?
1. Check out Google Gears SVN trunk as on
http://code.google.com/p/google-gears/source/checkout (I used Debian
testing (lenny))
2. Use make to attempt to build with Firefox.
3.

What is the expected output? What do you see instead?
Expected: successful build. Error:
g++ -I.. -Ibin-opt/linux-x86_64 -DPNG_USER_CONFIG -Ithird_party/zlib -
DNO_GZIP -DNO_GZCOMPRESS -Ithird_party/libgd -DLINUX -Ithird_party/gtk/
include/gtk-2.0 -Ithird_party/gtk/include/atk-1.0 -Ithird_party/gtk/
include/glib-2.0 -Ithird_party/gtk/include/pango-1.0 -Ithird_party/gtk/
include/cairo -Ithird_party/gtk/lib/gtk-2.0/include -Ithird_party/gtk/
lib/glib-2.0/include   -DNDEBUG=1 -c -o bin-opt/linux-x86_64/ff/
file_test.o -fPIC -fmessage-length=0 -Wall -O2 -fshort-wchar -fno-
exceptions -fno-rtti -Wno-non-virtual-dtor -Wno-ctor-dtor-privacy -
funsigned-char -DBROWSER_FF=1 -Ithird_party/gecko_1.8/linux -
Ithird_party/gecko_1.8/linux/gecko_sdk/include -Ithird_party/gecko_1.8
-DMOZILLA_STRICT_API  base/common/file_test.cc
base/common/file_test.cc: In function 'bool TestFileUtils()':
base/common/file_test.cc:58: error: 'TestSplitPath' was not declared
in this scope
make[1]: *** [bin-opt/linux-x86_64/ff/file_test.o] Error 1
make: *** [default] Error 2


What version of the product are you using? On what operating system?


Please provide any additional information below.

I have attached a patch that fixes the issue.
```

Original issue reported on code.google.com by `evilspor...@gmail.com` on 6 Mar 2008 at 7:21

Attachments:
- [fixsvn.patch](https://storage.googleapis.com/google-code-attachments/gears/issue-408/comment-0/fixsvn.patch)
